#!/usr/bin/env python3
"""Derive in-memory texture corrections from two Overseer surface captures.

The captures come from the same game build, once with the original R01.MAP and
once with the existing palette-patched R01.MAP. They are diagnostic inputs,
not files the installed wrapper needs at runtime.
"""

import argparse
import hashlib
import struct
from pathlib import Path

EXPECTED_BASE_CHANGES = {9: 12262, 10: 54847, 11: 1024, 12: 6918,
                         66: 131000, 67: 129680, 68: 261478}
EXPECTED_MIP_CHANGES = {18: 2956, 19: 720, 20: 13740, 21: 3447,
                        22: 256, 23: 64, 24: 1749, 25: 533,
                        132: 32750, 133: 8186, 134: 32390, 135: 8100,
                        136: 65376, 137: 16352}
FNV_OFFSET = 14695981039346656037
FNV_PRIME = 1099511628211


def read_capture(path):
    data = path.read_bytes()
    records = []
    offset = 0
    while offset + 20 <= len(data):
        magic, ordinal, width, height, pitch = struct.unpack_from(
            "<IIIII", data, offset)
        end = offset + 20 + pitch * height
        if magic != 0x53525631 or end > len(data) or pitch < width * 2:
            raise ValueError(f"Invalid capture record at {offset}")
        records.append((ordinal, width, height, pitch,
                        memoryview(data)[offset + 20:end]))
        offset = end
    if offset != len(data):
        raise ValueError(f"Trailing bytes in {path}")
    return records


def pixel_hash(raw, width, height, pitch):
    value = FNV_OFFSET
    for y in range(height):
        for byte in raw[y * pitch:y * pitch + width * 2]:
            value = ((value ^ byte) * FNV_PRIME) & ((1 << 64) - 1)
    return value


def rle(data):
    result = bytearray()
    at = 0
    while at < len(data):
        run = 1
        while at + run < len(data) and data[at + run] == data[at] and run < 128:
            run += 1
        if run >= 3:
            result.extend((0x80 | (run - 1), data[at]))
            at += run
            continue
        start = at
        at += run
        while at < len(data) and at - start < 128:
            next_run = 1
            while (at + next_run < len(data) and
                   data[at + next_run] == data[at] and next_run < 128):
                next_run += 1
            if next_run >= 3 or at - start + next_run > 128:
                break
            at += next_run
        result.append(at - start - 1)
        result.extend(data[start:at])
    return result


def emit_array(name, data):
    lines = [f"static const uint8_t {name}[] = {{"]
    for at in range(0, len(data), 16):
        lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in data[at:at + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def derive(original_path, patched_path, expected, kind):
    original = read_capture(original_path)
    patched = read_capture(patched_path)
    if len(original) != len(patched):
        raise ValueError("Capture record counts differ")
    entries = []
    for before, after in zip(original, patched):
        n, width, height, pitch, raw = before
        n2, width2, height2, pitch2, changed = after
        if (n, width, height, pitch) != (n2, width2, height2, pitch2):
            raise ValueError(f"Capture layout changed at record {n}")
        mask = bytearray((width * height + 7) // 8)
        count = 0
        for pos in range(width * height):
            offset = (pos // width) * pitch + 2 * (pos % width)
            old = struct.unpack_from("<H", raw, offset)[0]
            new = struct.unpack_from("<H", changed, offset)[0]
            if old != new:
                if new != 0x0842:
                    raise ValueError(f"Unexpected new color at record {n}")
                mask[pos // 8] |= 1 << (pos % 8)
                count += 1
        if count:
            if expected.get(n) != count:
                raise ValueError(f"Unexpected difference count at record {n}: {count}")
            entries.append((kind, n, width, height, pixel_hash(raw, width, height, pitch),
                            count, rle(mask)))
    if {entry[1] for entry in entries} != set(expected):
        raise ValueError("Changed surface set is incomplete")
    return entries


def generate(original_path, patched_path, original_mips, patched_mips,
             output_path):
    entries = derive(original_path, patched_path, EXPECTED_BASE_CHANGES, 0)
    entries += derive(original_mips, patched_mips, EXPECTED_MIP_CHANGES, 1)
    lines = ["/* Generated by generate_masks.py from the tested Overseer build.",
             f" * Base original SHA256: {hashlib.sha256(original_path.read_bytes()).hexdigest()}",
             f" * Base patched SHA256:  {hashlib.sha256(patched_path.read_bytes()).hexdigest()}",
             f" * Mips original SHA256: {hashlib.sha256(original_mips.read_bytes()).hexdigest()}",
             f" * Mips patched SHA256:  {hashlib.sha256(patched_mips.read_bytes()).hexdigest()}",
             " */", "#include \"texture_masks.h\"", ""]
    for kind, n, _, _, _, _, compressed in entries:
        lines.append(emit_array(f"mask_{kind}_{n}", compressed))
        lines.append("")
    lines.append("const struct overseer_mask overseer_masks[] = {")
    for kind, n, width, height, value, count, _ in entries:
        lines.append(f"  {{{kind}, {width}, {height}, UINT64_C(0x{value:016x}), "
                     f"{count}, mask_{kind}_{n}, sizeof(mask_{kind}_{n})}}, "
                     f"/* {'mip' if kind else 'base'} capture {n} */")
    lines.extend(["};", "const size_t overseer_mask_count =",
                  "    sizeof(overseer_masks) / sizeof(overseer_masks[0]);", ""])
    output_path.write_text("\n".join(lines))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("original", type=Path)
    parser.add_argument("patched", type=Path)
    parser.add_argument("original_mips", type=Path)
    parser.add_argument("patched_mips", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.original, args.patched, args.original_mips,
             args.patched_mips, args.output)
